version: '3.9'
services:
  db:
    image: postgres
    container_name: postgres-container
    environment:
      POSTGRES_DB: 'billinho_api-db'
      POSTGRES_USER: 'usuario'
      POSTGRES_PASSWORD: 'billinho'
    ports:
      - '5433:5433'
    volumes:
      - './data/postgres:/var/lib/postgresql/data' 
    networks:
      - compose-network
      
  pgadmin:
    image: dpage/pgadmin4
    container_name: 'pgadmin-container'
    environment:
      PGADMIN_DEFAULT_EMAIL: '<SEU USUARIO>'
      PGADMIN_DEFAULT_PASSWORD: '<SUA SENHA>'
    ports:
      - '15432:80'
    depends_on:
      - db
    networks:
      - compose-network
  billinho_api:
    build: .
    container_name: 'billinho_api'
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/billinho_api
    ports:
      - '3000:3000'
    depends_on:
      - db
    networks:
      - compose-network
networks: 
  compose-network:
    driver: bridge
  