# PostgreSQL. Versions 9.3 and up are supported.
default: &default
  host: db
  adapter: postgresql
  encoding: unicode
  username: usuario
  password: 'billinho'
development:
  <<: *default
  database: billinho_api_development
test:
  <<: *default
  database: billinho_api_test
production:
  <<: *default
  database: billinho_api_production
  